# known searchd commands
SEARCHD_COMMAND_SEARCH = 0
SEARCHD_COMMAND_EXCERPT = 1
SEARCHD_COMMAND_UPDATE = 2
SEARCHD_COMMAND_KEYWORDS = 3
SEARCHD_COMMAND_PERSIST = 4
SEARCHD_COMMAND_STATUS = 5
SEARCHD_COMMAND_FLUSHATTRS = 7

# current client-side command implementation versions
VER_COMMAND_SEARCH = 0x119
VER_COMMAND_EXCERPT = 0x104
VER_COMMAND_UPDATE = 0x102
VER_COMMAND_KEYWORDS = 0x100
VER_COMMAND_STATUS = 0x100
VER_COMMAND_FLUSHATTRS = 0x100

# known searchd status codes
SEARCHD_OK = 0
SEARCHD_ERROR = 1
SEARCHD_RETRY = 2
SEARCHD_WARNING = 3

# known match modes
SPH_MATCH_ALL = 0
SPH_MATCH_ANY = 1
SPH_MATCH_PHRASE = 2
SPH_MATCH_BOOLEAN = 3
SPH_MATCH_EXTENDED = 4
SPH_MATCH_FULLSCAN = 5
SPH_MATCH_EXTENDED2 = 6

ALL_MATCH_MODES = [
    SPH_MATCH_ALL,
    SPH_MATCH_ANY,
    SPH_MATCH_PHRASE,
    SPH_MATCH_BOOLEAN,
    SPH_MATCH_EXTENDED,
    SPH_MATCH_FULLSCAN,
    SPH_MATCH_EXTENDED2,
]

# known ranking modes (extended2 mode only)

# default mode, phrase proximity major factor and BM25 minor one
SPH_RANK_PROXIMITY_BM25 = 0
# statistical mode, BM25 ranking only (faster but worse quality)
SPH_RANK_BM25 = 1
# no ranking, all matches get a weight of 1
SPH_RANK_NONE = 2
# simple word-count weighting, rank is a weighted sum of per-field
# keyword occurence counts
SPH_RANK_WORDCOUNT = 3
SPH_RANK_PROXIMITY = 4
SPH_RANK_MATCHANY = 5
SPH_RANK_FIELDMASK = 6
SPH_RANK_SPH04 = 7
SPH_RANK_EXPR = 8

ALL_RANK_MODES = [
    SPH_RANK_WORDCOUNT,
    SPH_RANK_PROXIMITY,
    SPH_RANK_MATCHANY,
    SPH_RANK_FIELDMASK,
    SPH_RANK_SPH04,
    SPH_RANK_EXPR,
]


# known sort modes
SPH_SORT_RELEVANCE = 0
SPH_SORT_ATTR_DESC = 1
SPH_SORT_ATTR_ASC = 2
SPH_SORT_TIME_SEGMENTS = 3
SPH_SORT_EXTENDED = 4
SPH_SORT_EXPR = 5

ALL_SORT_MODES = [
    SPH_SORT_RELEVANCE,
    SPH_SORT_ATTR_DESC,
    SPH_SORT_ATTR_ASC,
    SPH_SORT_TIME_SEGMENTS,
    SPH_SORT_EXTENDED,
    SPH_SORT_EXPR,
]


# known filter types
SPH_FILTER_VALUES = 0
SPH_FILTER_RANGE = 1
SPH_FILTER_FLOATRANGE = 2

# known attribute types
SPH_ATTR_NONE = 0
SPH_ATTR_INTEGER = 1
SPH_ATTR_TIMESTAMP = 2
SPH_ATTR_ORDINAL = 3
SPH_ATTR_BOOL = 4
SPH_ATTR_FLOAT = 5
SPH_ATTR_BIGINT = 6
SPH_ATTR_STRING = 7
SPH_ATTR_MULTI = 0X40000001L
SPH_ATTR_MULTI64 = 0X40000002L

SPH_ATTR_TYPES = [
    SPH_ATTR_NONE,
    SPH_ATTR_INTEGER,
    SPH_ATTR_TIMESTAMP,
    SPH_ATTR_ORDINAL,
    SPH_ATTR_BOOL,
    SPH_ATTR_FLOAT,
    SPH_ATTR_BIGINT,
    SPH_ATTR_STRING,
    SPH_ATTR_MULTI,
    SPH_ATTR_MULTI64,
]

# known grouping functions
SPH_GROUPBY_DAY = 0
SPH_GROUPBY_WEEK = 1
SPH_GROUPBY_MONTH = 2
SPH_GROUPBY_YEAR = 3
SPH_GROUPBY_ATTR = 4
SPH_GROUPBY_ATTRPAIR = 5
